#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update

# install nginx
sudo apt-get -y install nginx

# Configure nginx to listen to port 80 aand return "Hello World!"
echo "server {
        listen 80;
        location / {
                return 200 'Hello World!\n';
        }
}" | sudo tee /etc/nginx/sites-available/default

# Restart nginx without systemctl
sudo service nginx restart
