#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# update repo
sudo apt update

# install ngnix
sudo apt -y install nginx

# start nginx
sudo service nginx start

# allow nginx
sudo ufw allow 'Nginx HTTP'

# allow privileges for modifying files in directtory
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server; 

        location / {
                try_files \$uri \$uri/ =404;
        }

}" | sudo tee /etc/nginx/sites-enabled/default

# Restart nginx without systemctl
sudo service nginx restart
