#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update

# install nginx specific version
sudo apt-get -y install nginx=1.4.*

# Configure nginx to listen to port 80 aand return "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart nginx without systemctl
sudo service nginx restart
