#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update

# install nginx
sudo apt-get -y install nginx

sudo sed -i '/^}/ i\\tlocation /redirect_me {\n\t\trewrite ^/redirect_me/?$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}' /etc/nginx/sites-enabled/default

# Restart nginx without systemctl
sudo service nginx restart

# check for errors in nginx server block file
sudo nginx -t

# restart nginx service
sudo service nginx restart