#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt update

sudo apt -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/redirect_me/html

echo "server {
        listen 80;

        location / {
                return 200 'Hello World!';
        }
        rewrite ^/redirect_me$ http://youtube.com permanent;

}" | sudo tee /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart