#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# update repo
sudo apt update

# install ngnix
sudo apt -y install nginx

# start nginx
sudo service nginx start

# allow nginx
sudo ufw allow 'Nginx HTTP'

# allow privileges for modifying files in directtory
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server; 

        location / {
                return 200 'Hello World!';
        }
        rewrite ^/redirect_me/$ http://youtube.com permanent;

}" | sudo tee /etc/nginx/sites-enabled/default

# check for errors in nginx server block file
sudo nginx -t

sudo service nginx restart