#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt update

# Install nginx
sudo apt -y install nginx

# allow nginx on port 80
sudo ufw allow 'Nginx HTTP'

# create parent dir for 404 page
# sudo mkdir -p /var/www/404/html

# create 404 html custom page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

echo "server {
        listen 80;

        location / {
                return 200 'Hello World!';
        }
        location /redirect_me {
                return 301 https://youtube.com;
        }

        error_page 404 /custom_404.html;

        location = /custom_404.html {
            internal;
        }
}" | sudo tee /etc/nginx/sites-available/default

# check for error in nginx file
sudo nginx -t

# restart nginx
sudo service nginx restart