#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# update repo
sudo apt update > /dev/null 2>&1

# install ngnix
sudo apt -y install nginx > /dev/null 2>&1

# allow nginx
sudo ufw allow 'Nginx HTTP' > /dev/null 2>&1

# default page and redirect page
echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.wanyama-tech.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# error 404 custom page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default


# check for error in nginx file
sudo nginx -t > /dev/null 2>&1

# restart nginx
sudo service nginx restart