#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# update repo
sudo apt update

# install ngnix
sudo apt -y install nginx

# allow nginx
sudo ufw allow 'Nginx HTTP'

# create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# edit nginx server block file
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        location / {
                try_files \$uri \$uri/ =404;
        }

        location /redirect_me/ {
                return 301 http://youtube.com;
        }

        error_page 404 /custom_404.html;
        location = {
                root /var/www/html;
                internal;
        }

}" | sudo tee /etc/nginx/sites-enabled/default

# check for error in nginx file
sudo nginx -t

# restart nginx
sudo service nginx restart