#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine to the requirements asked in this task
# Ignore SC2154 for shellcheck

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to serve "Hello World!" at the root
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# sudo bash -c 'echo "Ceci n'est pas une page" > /var/www/html/custom_404.html'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Add redirection from /redirect_me to another page
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name _;

        root /var/www/html;
        index index.htm index.html index.nginx-debian.html;

        location / {
                try_files \$uri \$uri/ =404;
                add_header X-Served-By \$hostname;
        }
        rewrite ^/redirect_me/?$ http://wanyama-ken.tech/ permanent;

        error_page 404 /custom_404.html;
        location = /custom_404.html {
            internal;
        }

}" | sudo tee /etc/nginx/sites-enabled/default

# Restart Nginx without using systemctl
sudo service nginx restart