#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# u[pdate] repository
sudo apt-get update

# install haproxy
sudo apt-get -y install haproxy

echo "frontend http_front
        bind *:80
        stats uri /haproxy?stats
        default_backend http_back
      
      backend roundrobin
        balance roundrobin
        server web-01 100.26.162.188:80 check
        server web-02 100.25.171.248:80 check
        " | sudo tee /etc/haproxy/haproxy.cfg > /dev/null 2>&1

# start haproxy service
sudo service haproxy start