#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# update the repo
sudo apt update
#install haproxy
sudo apt -y install haproxy

# configure backend and frontend for load balancer
echo "frontend http
        bind *:80
        mode http
        default_backend alx-se
backend alx-se
    mode http
    balance roundrobin
    server web-01 54.158.192.203:80 check
    server web-02 18.234.253.58:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# restart haproxy
sudo service haproxy restart
