#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
# Requirements:
# - Your Bash script must be 5 lines long or less

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"