#!/usr/bin/env bash
# Bash script that displays:
#   The content of the current directory
#   In a list format
#   Where only the part of the name after the first dash is
#       displayed (refer to the example)
for file in *; do
    if [ -f "$file" ] && [[ $file == *-* ]]; then
        # Extract the part of the name after the first dash
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_after_dash"
    fi
done