#!/usr/bin/env bash
# Bash script that displays:
#   The content of the current directory
#   In a list format
#   Where only the part of the name after the first dash is
#       displayed (refer to the example)
files="ls -A1"
for file in $files; do
    if [[ $file == *- ]]
    then
        filename=${file##*-}
        echo "$filename"
    fi
done
